apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 'services'
spec:
  project: default
  source:
    repoURL: https://github.com/acidonpe/ocp-argo-applicationsets.git
    targetRevision: HEAD
    path: '.'
  destination:
    server: https://kubernetes.default.svc
    namespace: '{{path.basename}}'