apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 'services'
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: https://github.com/acidonper/ocp-gitops-argocd-applicationsets.git
    targetRevision: HEAD
    path: '.'
  destination:
    server: https://kubernetes.default.svc
    namespace: 'openshift-gitops'
  syncPolicy:
    automated:
      prune: true